# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [67]:
import pandas as pd
import numpy as np

## imports for Python, Pandas

In [2]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [3]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [4]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [5]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [6]:
# load json as string
json.load((open('world_bank_projects_less.json')))

[{'_id': {'$oid': '52b213b38594d8a2be17c780'},
  'approvalfy': 1999,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-12T00:00:00Z',
  'borrower': 'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA',
  'closingdate': '2018-07-07T00:00:00Z',
  'country_namecode': 'Federal Democratic Republic of Ethiopia!$!ET',
  'countrycode': 'ET',
  'countryname': 'Federal Democratic Republic of Ethiopia',
  'countryshortname': 'Ethiopia',
  'docty': 'Project Information Document,Indigenous Peoples Plan,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 0,
  'ibrdcommamt': 0,
  'id': 'P129828',
  'idacommamt': 130000000,
  'impagency': 'MINISTRY OF EDUCATION',
  'lendinginstr': 'Investment Project Financing',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 550000000,
  'majorsector_percent': [{'Name': 'Education', 'Percent': 46},
   {'Name': 'Education', 'Percent': 26},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 16},
   {'Name': 'Education', 'Percent': 12}],
  'mjsector_namecode': [{'code': 'EX', 'name': 'Education'},
   {'code': 'EX', 'name': 'Education'},
   {'code': 'BX', 'name': 'Public Administration, Law, and Justice'},
   {'code': 'EX', 'name': 'Education'}],
  'mjtheme': ['Human development'],
  'mjtheme_namecode': [{'code': '8', 'name': 'Human development'},
   {'code': '11', 'name': ''}],
  'mjthemecode': '8,11',
  'prodline': 'PE',
  'prodlinetext': 'IBRD/IDA',
  'productlinetype': 'L',
  'project_abstract': {'cdata': 'The development objective of the Second Phase of General Education Quality Improvement Project for Ethiopia is to improve learning conditions in primary and secondary schools and strengthen institutions at different levels of educational administration. The project has six components. The first component is curriculum, textbooks, assessment, examinations, and inspection. This component will support improvement of learning conditions in grades KG-12 by providing increased access to teaching and learning materials and through improvements to the curriculum by assessing the strengths and weaknesses of the current curriculum. This component has following four sub-components: (i) curriculum reform and implementation; (ii) teaching and learning materials; (iii) assessment and examinations; and (iv) inspection. The second component is teacher development program (TDP). This component will support improvements in learning conditions in both primary and secondary schools by advancing the quality of teaching in general education through: (a) enhancing the training of pre-service teachers in teacher education institutions; and (b) improving the quality of in-service teacher training. This component has following three sub-components: (i) pre-service teacher training; (ii) in-service teacher training; and (iii) licensing and relicensing of teachers and school leaders. The third component is school improvement plan. This component will support the strengthening of school planning in order to improve learning outcomes, and to partly fund the school improvement plans through school grants. It has following two sub-components: (i) school improvement plan; and (ii) school grants. The fourth component is management and capacity building, including education management information systems (EMIS). This component will support management and capacity building aspect of the project. This component has following three sub-components: (i) capacity building for education planning and management; (ii) capacity building for school planning and management; and (iii) EMIS. The fifth component is improving the quality of learning and teaching in secondary schools and universities through the use of information and communications technology (ICT). It has following five sub-components: (i) national policy and institution for ICT in general education; (ii) national ICT infrastructure improvement plan for general education; (iii) develop an integrated monitoring, evaluation, and learning system specifically for the ICT component; (iv) teacher professional development in the use of ICT; and (v) provision of limited number of e-Braille display readers with the possibility to scale up to all secondary education schools based on the successful implementation and usage of the readers. The sixth component is program coordination, monitoring and evaluation, and communication. It will support institutional strengthening by developing capacities in all aspects of program coordination, monitoring and evaluation; a new sub-component on communications will support information sharing for better management and accountability. It has following three sub-components: (i) program coordination; (ii) monitoring and evaluation (M and E); and (iii) communication.'},
  'project_name': 'Ethiopia General Education Quality Improvement Project II',
  'projectdocs': [{'DocDate': '28-AUG-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b081e545fb_1_0',
    'EntityID': '090224b081e545fb_1_0'},
   {'DocDate': '01-JUL-2013',
    'DocType': 'IP',
    'DocTypeDesc': 'Indigenous Peoples Plan (IP),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20130920111729',
    'EntityID': '000442464_20130920111729'},
   {'DocDate': '22-NOV-2012',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b0817b19e2_1_0',
    'EntityID': '090224b0817b19e2_1_0'}],
  'projectfinancialtype': 'IDA',
  'projectstatusdisplay': 'Active',
  'regionname': 'Africa',
  'sector': [{'Name': 'Primary education'},
   {'Name': 'Secondary education'},
   {'Name': 'Public administration- Other social services'},
   {'Name': 'Tertiary education'}],
  'sector1': {'Name': 'Primary education', 'Percent': 46},
  'sector2': {'Name': 'Secondary education', 'Percent': 26},
  'sector3': {'Name': 'Public administration- Other social services',
   'Percent': 16},
  'sector4': {'Name': 'Tertiary education', 'Percent': 12},
  'sector_namecode': [{'code': 'EP', 'name': 'Primary education'},
   {'code': 'ES', 'name': 'Secondary education'},
   {'code': 'BS', 'name': 'Public administration- Other social services'},
   {'code': 'ET', 'name': 'Tertiary education'}],
  'sectorcode': 'ET,BS,ES,EP',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Education for all', 'Percent': 100},
  'theme_namecode': [{'code': '65', 'name': 'Education for all'}],
  'themecode': '65',
  'totalamt': 130000000,
  'totalcommamt': 130000000,
  'url': 'http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en'},
 {'_id': {'$oid': '52b213b38594d8a2be17c781'},
  'approvalfy': 2015,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-04T00:00:00Z',
  'borrower': 'GOVERNMENT OF TUNISIA',
  'country_namecode': 'Republic of Tunisia!$!TN',
  'countrycode': 'TN',
  'countryname': 'Republic of Tunisia',
  'countryshortname': 'Tunisia',
  'docty': 'Project Information Document,Integrated Safeguards Data Sheet,Integrated Safeguards Data Sheet,Project Information Document,Integrated Safeguards Data Sheet,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 4700000,
  'ibrdcommamt': 0,
  'id': 'P144674',
  'idacommamt': 0,
  'impagency': 'MINISTRY OF FINANCE',
  'lendinginstr': 'Specific Investment Loan',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 5700000,
  'majorsector_percent': [{'Name': 'Public Administration, Law, and Justice',
    'Percent': 70},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 30}],
  'mjsector_namecode': [{'code': 'BX',
    'name': 'Public Administration, Law, and Justice'},
   {'code': 'BX', 'name': 'Public Administration, Law, and Justice'}],
  'mjtheme': ['Economic management', 'Social protection and risk management'],
  'mjtheme_namecode': [{'code': '1', 'name': 'Economic management'},
   {'code': '6', 'name': 'Social protection and risk management'}],
  'mjthemecode': '1,6',
  'prodline': 'RE',
  'prodlinetext': 'Recipient Executed Activities',
  'productlinetype': 'L',
  'project_name': 'TN: DTF Social Protection Reforms Support',
  'projectdocs': [{'DocDate': '29-MAR-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131024115616',
    'EntityID': '000333037_20131024115616'},
   {'DocDate': '29-MAR-2013',
    'DocType': 'ISDS',
    'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20131024151611',
    'EntityID': '000356161_20131024151611'},
   {'DocDate': '29-MAR-2013',
    'DocType': 'ISDS',
    'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20131031112136',
    'EntityID': '000442464_20131031112136'},
   {'DocDate': '29-MAR-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131031105716',
    'EntityID': '000333037_20131031105716'},
   {'DocDate': '16-JAN-2013',
    'DocType': 'ISDS',
    'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113209',
    'EntityID': '000356161_20130305113209'},
   {'DocDate': '16-JAN-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113716',
    'EntityID': '000356161_20130305113716'}],
  'projectfinancialtype': 'OTHER',
  'projectstatusdisplay': 'Active',
  'regionname': 'Middle East and North Africa',
  'sector': [{'Name': 'Public administration- Other social services'},
   {'Name': 'General public administration sector'}],
  'sector1': {'Name': 'Public administration- Other social services',
   'Percent': 70},
  'sector2': {'Name': 'General public administration sector', 'Percent': 30},
  'sector_namecode': [{'code': 'BS',
    'name': 'Public administration- Other social services'},
   {'code': 'BZ', 'name': 'General public administration sector'}],
  'sectorcode': 'BZ,BS',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Other economic management', 'Percent': 30},
  'theme_namecode': [{'code': '24', 'name': 'Other economic management'},
   {'code': '54', 'name': 'Social safety nets'}],
  'themecode': '54,24',
  'totalamt': 0,
  'totalcommamt': 4700000,
  'url': 'http://www.worldbank.org/projects/P144674?lang=en'}]

In [7]:
# load as Pandas dataframe
sample_json_df = pd.read_json('world_bank_projects_less.json')
sample_json_df

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Name': 'Education for all', 'Percent': 100}","[{'name': 'Education for all', 'code': '65'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Name': 'Other economic management', 'Percent...","[{'name': 'Other economic management', 'code':...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

#### Find the 10 countries with most projects

In [8]:
# Reading world_bank_projects.json into a dataframe
x = pd.read_json('world_bank_projects.json')
x

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Percent': 30, 'Name': 'Other economic manage...","[{'code': '24', 'name': 'Other economic manage...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{'$oid': '52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,TI,IBRD,Active,Y,"{'Percent': 46, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{'$oid': '52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of",...,JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Participation and civ...","[{'code': '57', 'name': 'Participation and civ...","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{'$oid': '52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,...,"FH,YW,YZ",IBRD,Active,N,"{'Percent': 30, 'Name': 'Export development an...","[{'code': '45', 'name': 'Export development an...","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...
5,{'$oid': '52b213b38594d8a2be17c785'},2014,October,2013-10-31T00:00:00Z,REPUBLIC OF KENYA,NaN,Republic of Kenya!$!KE,KE,Republic of Kenya,Kenya,...,JB,IBRD,Active,Y,"{'Percent': 100, 'Name': 'Social safety nets'}","[{'code': '54', 'name': 'Social safety nets'}]",54,10000000,10000000,http://www.worldbank.org/projects/P146161?lang=en
6,{'$oid': '52b213b38594d8a2be17c786'},2014,October,2013-10-29T00:00:00Z,GOVERNMENT OF INDIA,2019-06-30T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,TI,IBRD,Active,N,"{'Percent': 20, 'Name': 'Administrative and ci...","[{'code': '25', 'name': 'Administrative and ci...","39,25",500000000,500000000,http://www.worldbank.org/projects/P121185/firs...
7,{'$oid': '52b213b38594d8a2be17c787'},2014,October,2013-10-29T00:00:00Z,PEOPLE'S REPUBLIC OF CHINA,NaN,People's Republic of China!$!CN,CN,People's Republic of China,China,...,LR,IBRD,Active,N,"{'Percent': 100, 'Name': 'Climate change'}","[{'code': '81', 'name': 'Climate change'}]",81,0,27280000,http://www.worldbank.org/projects/P127033/chin...
8,{'$oid': '52b213b38594d8a2be17c788'},2014,October,2013-10-29T00:00:00Z,THE GOVERNMENT OF INDIA,2018-12-31T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,TI,IBRD,Active,N,"{'Percent': 87, 'Name': 'Other rural developme...","[{'code': '79', 'name': 'Other rural developme...",79,160000000,160000000,http://www.worldbank.org/projects/P130164/raja...
9,{'$oid': '52b213b38594d8a2be17c789'},2014,October,2013-10-29T00:00:00Z,THE KINGDOM OF MOROCCO,2014-12-31T00:00:00Z,Kingdom of Morocco!$!MA,MA,Kingdom of Morocco,Morocco,...,"BM,BC,BZ",IBRD,Active,N,"{'Percent': 33, 'Name': 'Other accountability/...","[{'code': '29', 'name': 'Other accountability/...","27,30,29",200000000,200000000,http://www.worldbank.org/projects/P130903?lang=en
10,{'$oid': '52b213b38594d8a2be17c78a'},2014,October,2013-10-25T00:00:00Z,GOVERNMENT OF SOUTH SUDAN,NaN,Republic of South Sudan!$!SS,SS,Republic of South Sudan,South Sudan,...,"AZ,JB,AH",IBRD,Active,Y,"{'Percent': 100, 'Name': 'Global food crisis r...","[{'code': '91', 'name': 'Global food crisis re...",91,0,7530000,http://www.worldbank.org/projects/P145339?lang=en
11,{'$oid': '52b213b38594d8a2be17c78b'},2014,October,2013-10-25T00:00:00Z,NaN,2017-12-31T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,"JB,YC,WD,TI",IBRD,Active,N,"{'Percent': 60, 'Name': 'Rural services and in...","[{'code': '78', 'name': 'Rural services and in...","81,87,52,78",250000000,250000000,http://www.worldbank.org/projects/P146653?lang=en
12,{'$oid': '52b213b38594d8a2be17c78c'},2014,October,2013-10-24T00:00:00Z,GOVERNMENT OF GHANA,2019-06-30T00:00:00Z,Republic of Ghana!$!GH,GH,Republic of Ghana,Ghana,...,CZ,IBRD,Active,N,"{'Percent': 0, 'Name': ''}",NaN,NaN,97000000,97000000,http://www.worldbank.org/projects/P144140/gh-e...
13,{'$oid': '52b213b38594d8a2be17c78d'},2014,October,2013-10-22T00:00:00Z,GOVERNMENT OF TIMOR LESTE,NaN,Democratic Republic of Timor-Leste!$!TP,TP,Democratic Republic of Timor-Leste,Timor-Leste,...,"BV,TI",IBRD,Active,Y,"{'Percent': 20, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","78,81,47",40000000,40000000,http://www.worldbank.org/projects/P130975/timo...
14,{'$oid': '52b213b38594d8a2be17c78e'},2014,October,2013-10-22T00:00:00Z,GOVERNMENT OF JORDAN,NaN,Hashemite Kingdom of Jordan!$!JO,JO,Hashemite Kingdom of Jordan,Jordan,...,JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Social safety nets'}","[{'code': '54', 'name': 'Social safety nets'},...","53,56,54",0,9500000,http://www.worldbank.org/projects/P144832?lang=en
15,{'$oid': '52b213b38594d8a2be17c78f'},2014,October,2013-10-17T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Samoa!$!WS,WS,Samoa,Samoa,...,TI,IBRD,Active,N,"{'Percent': 60, 'Name': 'Rural services and in...","[{'code': '78', 'name': 'Rural services and in...","49,81,78",20000000,20000000,http://www.worldbank.org/projects/P145545?lang=en
16,{'$oid': '52b213b38594d8a2be17c790'},2014,October,2013-10-17T00:00:00Z,MINISTRY OF FINANCE,2015-12-31T00:00:00Z,Samoa!$!WS,WS,Samoa,Samoa,...,"AZ,AJ,AH",IBRD,Active,N,"{'Percent': 100, 'Name': 'Other rural developm...","[{'code': '79', 'name': 'Other rural developme...",79,5000000,5000000,http://www.worldbank.org/projects/P145938?lang=en
17,{'$oid': '52b213b38594d8a2be17c791'},2014,October,2013-10-16T00:00:00Z,MINISTRY OF FINANCE AND BUDGET (MFB),NaN,Republic of Madagascar!$!MG,MG,Republic of Madagascar,Madagascar,...,EP,IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,0,85400000,http://www.worldbank.org/projects/P132616?lang=en
18,{'$oid': '52b213b38594d8a2be17c792'},2014,October,2013-10-16T00:00:00Z,ROYAL GOVERNMENT OF CAMBODIA,NaN,Kingdom of Cambodia!$!KH,KH,Kingdom of Cambodia,Cambodia,...,"BK,JB,BH,BC,JA",IBRD,Active,Y,"{'Percent': 17, 'Name': 'Child health'}","[{'code': '63', 'name': 'Child health'}, {'cod...","69,57,25,67,63",0,13450000,http://www.worldbank.org/projects/P146271?lang=en
19,{'$oid': '52b213b38594d8a2be17c793'},2014,October,2013-10-10T00:00:00Z,MINISTRY OF FINANCE,NaN,Kingdom of Morocco!$!MA,MA,Kingdom of Morocco,Morocco,...,"BH,BC,BZ",IBRD,Active,N,"{'Percent': 40, 'Name': 'Public expenditure, f...","[{'code': '27', 'name': 'Public expenditure, f...","25,26,27",0,4350000,http://www.worldbank.org/projects/P143979?lang=en
20,{'$oid': '52b213b38594d8a2be17c794'},2014,October,2013-10-09T00:00:00Z,AGA KHAN DEVELOPMENT NETWORK (AKDN),NaN,Kyrgyz Republic!$!KG,KG,Kyrgyz Republic,Kyrgyz Republic,...,JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Conflict prevention a...","[{'code': '58', 'name': 'Conflict prevention a...","57,58",0,2000000,http://www.worldbank.org/projects/P132577?lang=en
21,{'$oid': '52b213b38594d8a2be17c795'},2014,October,2013-10-07T00:00:00Z,NEPAL,NaN,Nepal!$!NP,NP,Nepal,Nepal,...,"BH,YW,JB",IBRD,Active,N,"{'Percent': 30, 'Name': 'Urban services and ho...","[{'code': '71', 'name': 'Urban services and ho...","57,71",0,2750000,http://www.worldbank.org/projects/P145359?lang=en
22,{'$oid': '52b213b38594d8a2be17c796'},2014,October,2013-10-07T00:00:00Z,MINISTRY OF PLANNING AND INTERNATIONAL C,NaN,Hashemite Kingdom of Jordan!$!JO,JO,Hashemite Kingdom of Jordan,Jordan,...,"WC,BS,BH,TZ,WB",IBRD,Active,N,"{'Percent': 25, 'Name': 'Other social developm...","[{'code': '62', 'name': 'Other social developm...","58,62",0,50000000,http://www.worldbank.org/projects/P147689?lang=en
23,{'$oid': '52b213b38594d8a2be17c797'},2014,October,2013-10-03T00:00:00Z,REPUBLIC OF TAJIKISTAN,NaN,Republic of Tajikistan!$!TJ,TJ,Republic of Tajikistan,Tajikistan,...,JA,IBRD,Active,N,"{'Percent': 60, 'Name': 'Nutrition and food se...","[{'code': '68', 'name': 'Nutrition and food se...","63,68",0,2800000,http://www.worldbank.org/projects/P146109?lang=en
24,{'$oid': '52b213b38594d8a2be17c798'},2014,September,2013-09-30T00:00:00Z,REPUBLIC OF AZERBAIJAN,2018-12-31T00:00:00Z,Republic of Azerbaijan!$!AZ,AZ,Republic of Azerbaijan,Azerbaijan,...,"AB,AZ,YA",IBRD,Active,N,"{'Percent': 30, 'Name': 'Rural markets'}","[{'code': '75', 'name': 'Rural markets'}, {'co...","56,78,76,75",34500000,34500000,http://www.worldbank.org/projects/P122812/thir...
25,{'$oid': '52b213b38594d8a2be17c799'},2014,September,2013-09-30T00:00:00Z,UNIVERSITY OF QUEENSLAND,NaN,East Asia and Pacific!$!4E,4E,East Asia and Pacific,East Asia and Pacific,...,"AB,AZ",IBRD,Active,N,"{'Percent': 40, 'Name': 'Other environment and...","[{'code': '86', 'name': 'Other environment and...","80,81,86",0,4500000,http://www.worldbank.org/projects/P123933/capt...
26,{'$oid': '52b213b38594d8a2be17c79a'},2014,September,2013-09-30T00:00:00Z,LAO PEOPLES DEMOCRATIC REPUBLIC,2014-03-31T00:00:00Z,Lao People's Democratic Republic!$!LA,LA,Lao People's Democratic Republic,Lao People's Democratic Republic,...,"LG,FB,EZ,YZ,BC",IBRD,Closed,N,"{'Percent': 14, 'Name': 'Regulation and compet...","[{'code': '40', 'name': 'Regulation and compet...","67,27,49,40",20000000,20000000,http://www.worldbank.org/projects/P143025/lao-...
27,{'$oid': '52b213b38594d8a2be17c79b'},2014,September,2013-09-30T00:00:00Z,PACIFIC AVIATION SECURITY OFFICE,2018-12-31T00:00:00Z,Pacific Islands!$!4P,4P,Pacific Islands,Pacific Islands,...,"BV,TV",IBRD,Active,N,"{'Percent': 5, 'Name': 'Climate change'}","[{'code': '81', 'name': 'Climate change'}, {'c...","52,47,25,81",2150000,2150000,http://www.worldbank.org/projects/P145057/paci...
28,{'$oid': '52b213b38594d8a2be17c79c'},2014,September,2013-09-30T00:00:00Z,SOLOMON ISLANDS GOVERNMENT,NaN,Solomon Islands!$!SB,SB,Solomon Islands,Solomon Islands,...,"BZ,AZ",IBRD,Active,Y,"{'Percent': 30, 'Name': 'Rural policies and in...","[{'code': '77', 'name': 'Rural policies and in...","57,78,77",3000000,3000000,http://www.worldbank.org/projects/P146021?lang=en
29,{'$oid': '52b213b38594d8a2be17c79d'},2014,September,2013-09-27T00:00:00Z,GOVERNMENT OF MOZAMBIQUE,NaN,Republic of Mozambique!$!MZ,MZ,Republic of Mozambique,Mozambique,...,"JB,BW,WZ,WD",IBRD,Active,Y,"{'Percent': 4, 'Name': 'Other social developme...","[{'code': '62', 'name': 'Other social developm...","85,62",32000000,32000000,http://www.worldbank.org/projects/P146098?lang=en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,{'$oid': '52b213b38594d8a2be17c956'},2013,September,2012-09-20T00:00:00Z,GOVERNMENT OF LIBERIA,NaN,Republic of Liberia!$!LR,LR,Republic of Liberia,Liberia,...,"BV,TI",IBRD,Active,Y,"{'Percent': 40, 'Name': 'Trade facilitation an...","[{'code': '49', 'name': 'Trade facilitation an...","78,49",50000000,50000000,http://www.worldbank.org/projects/P129654/libe...
471,{'$oid': '52b213b38594d8a2be17c957'},2013,September,2012-09-20T00:00:00Z,GOVERNMENT OF BANGLADESH,2018-12-31T00:00:00Z,People's Republic of Bangladesh!$!BD,BD,People's Republic of Bangladesh,Bangladesh,...,"BU,LA,LR",IBRD,Active,N,"{'Percent': 45, 'Name': 'Rural services and in...","[{'code': '78', 'name': 'Rural services and in...","59,81,57,78",155000000,155000000,http://www.worldbank.org/projects/P131263/rura...
472,{'$oid': '52b213b38594d8a2be17c958'},2013,September,2012-09-13T00:00:00Z,MINISTRY OF NATURE PROTECTION,2014-09-30T00:00:00Z,Republic of Armenia!$!AM,AM,Republic of Armenia,Armenia,...,BC,IBRD,Active,N,"{'Percent': 100, 'Name': 'Other environment an...","[{'code': '86', 'name': 'Other environment and...",86,0,150000,http://www.worldbank.org/projects/P131631/repo...
473,{'$oid': '52b213b38594d8a2be17c959'},2013,September,2012-09-13T00:00:00Z,"MINISTRY OF ENVIRONMENT, FORESTS, WATER",NaN,Republic of Albania!$!AL,AL,Republic of Albania,Albania,...,BC,IBRD,Active,N,"{'Percent': 100, 'Name': 'Other environment an...","[{'code': '86', 'name': 'Other environment and...",86,0,150000,http://www.worldbank.org/projects/P132679/land...
474,{'$oid': '52b213b38594d8a2be17c95a'},2013,September,2012-09-11T00:00:00Z,GOVERNMENT OF PAKISTAN,2017-06-30T00:00:00Z,Islamic Republic of Pakistan!$!PK,PK,Islamic Republic of Pakistan,Pakistan,...,"BM,BH",IBRD,Active,N,"{'Percent': 34, 'Name': 'Municipal finance'}","[{'code': '72', 'name': 'Municipal finance'}, ...","73,72",150000000,150000000,http://www.worldbank.org/projects/P112901/pk-p...
475,{'$oid': '52b213b38594d8a2be17c95b'},2013,September,2012-09-11T00:00:00Z,GOVERNMENT OF INDONESIA,2018-03-31T00:00:00Z,Republic of Indonesia!$!ID,ID,Republic of Indonesia,Indonesia,...,"BO,BH,LZ,TZ,WZ",IBRD,Active,N,"{'Percent': 25, 'Name': 'Infrastructure servic...","[{'code': '39', 'name': 'Infrastructure servic...","72,39",29600000,29600000,http://www.worldbank.org/projects/P118916/infr...
476,{'$oid': '52b213b38594d8a2be17c95c'},2013,September,2012-09-11T00:00:00Z,SOCIALIST REPUBLIC OF VIETNAM,2018-12-31T00:00:00Z,Socialist Republic of Vietnam!$!VN,VN,Socialist Republic of Vietnam,Vietnam,...,"BU,LT,LA",IBRD,Active,N,"{'Percent': 100, 'Name': 'Rural services and i...","[{'code': '78', 'name': 'Rural services and in...",78,448900000,448900000,http://www.worldbank.org/projects/P125996/dist...
477,{'$oid': '52b213b38594d8a2be17c95d'},2013,September,2012-09-11T00:00:00Z,REPUBLIC OF UZBEKISTAN,NaN,Republic of Uzbekistan!$!UZ,UZ,Republic of Uzbekistan,Uzbekistan,...,FH,IBRD,Active,Y,"{'Percent': 40, 'Name': 'Micro, Small and Medi...","[{'code': '41', 'name': 'Micro, Small and Medi...","75,41",40000000,40000000,http://www.worldbank.org/projects/P126962/addi...
478,{'$oid': '52b213b38594d8a2be17c95e'},2013,September,2012-09-11T00:00:00Z,ISLAMIC REPUBLIC OF PAKISTAN,NaN,Islamic Republic of Pakistan!$!PK,PK,Islamic Republic of Pakistan,Pakistan,...,BH,IBRD,Active,Y,"{'Percent': 10, 'Name': 'Administrative and ci...","[{'code': '25', 'name': 'Administrative and ci...","83,36,25",70000000,70000000,http://www.worldbank.org/projects/P131266/punj...
479,{'$oid': '52b213b38594d8a2be17c95f'},2013,September,2012-09-10T00:00:00Z,UT'Z CHE,2016-05-07T00:00:00Z,Republic of Guatemala!$!GT,GT,Republic of Guatemala,Guatemala,...,AZ,IBRD,Active,N,"{'Percent': 100, 'Name': 'Other social develop...","[{'code': '62', 'name': 'Other social developm...",62,0,2510000,http://www.worldbank.org/projects/P130412/stre...
480,{'$oid': '52b213b38594d8a2be17c960'},2013,September,2012-09-10T00:00:00Z,GOVERNMENT OF ZAMBIA,2014-12-31T00:00:00Z,Republic of Zambia!$!ZM,ZM,Republic of Zambia,Zambia,...,LS,IBRD,Active,N,"{'Percent': 100, 'Name': 'Other public sector ...","[{'code': '30', 'name': 'Other public sector g...",30,0,350000,http://www.worldbank.org/projects/P131881/zamb...
481,{'$oid': '52b213b38594d8a2be17c961'},2013,September,2012-09-06T00:00:00Z,GOVERNMENT OF INDIA,2015-12-31T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,"BC,EC,BQ,BH",IBRD,Active,N,"{'Percent': 23, 'Name': 'Child health'}","[{'code': '63', 'name': 'Child health'}, {'cod...","68,59,57,63",106000000,106000000,http://www.worldbank.org/projects/P121731/icds...
482,{'$oid': '52b213b38594d8a2be17c962'},2013,September,2012-09-06T00:00:00Z,GOVERNMENT OF INDIA,2018-12-31T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,"AI,YA,AH,BL,AB",IBRD,Active,N,"{'Percent': 10, 'Name': 'Rural services and in...","[{'code': '78', 'name': 'Rural services and in...","79,85,86,78",60000000,60000000,http://www.worldbank.org/projects/P122486/karn...
483,{'$oid': '52b213b38594d8a2be17c963'},2013,September,2012-09-06T00:00:00Z,GOVERNMENT OF INDIA,2013-09-30T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,"CZ,AH,LA,AI,LH",IBRD,Closed,N,"{'Percent': 19, 'Name': 'Pollution management ...","[{'code': '84', 'name': 'Pollution management ...","82,78,81,84",100000000,100000000,http://www.worldbank.org/projects/P124041/hima...
484,{'$oid': '52b213b38594d8a2be17c964'},2013,September,2012-09-06T00:00:00Z,"ILO, MINLAND & CFSI & BANK",2015-12-31T00:00:00Z,Republic of the Philippines!$!PH,PH,Republic of the Philippines,Philippines,...,"EV,FH,BZ,JB",IBRD,Active,Y,"{'Percent': 9, 'Name': 'Rural non-farm income ...","[{'code': '76', 'name': 'Rural non-farm income...","78,58,41,76",0,5570000,http://www.worldbank.org/projects/P132238/mult...
485,{'$oid': '52b213b38594d8a2be17c965'},2013,September,2012-09-05T00:00:00Z,GOVERNMENT OF MONGOLIA,2013-12-31T00:00:00Z,Mongolia!$!MN,MN,Mongolia,Mongolia,...,"BZ,JA,AJ",IBRD,Active,N,"{'Percent': 100, 'Name': 'Other communicable d...","[{'code': '64', 'name': 'Other communicable di...",64,0,2900000,http://www.worldbank.org/projects/P131204/capa...
486,{'$oid': '52b213b38594d8a2be17c966'},2013,September,2012-09-01T00:00:00Z,GOVERNMENT OF LEBANON & JORDAN,2015-01-31T00:00:00Z,Middle East and North Africa!$!5M,5M,Middle East and North Africa,Middle East and North Africa,...,"BZ,BS,BQ,BN",IBRD,Active,N,"{'Percent': 25, 'Name': 'Other public sector g...","[{'code': '30', 'name': 'Other public sector g...","54,55,56,30",0,2400000,http://www.worldbank.org/projects/P132097/5m-d...
487,{'$oid': '52b213b38594d8a2be17c967'},2013,August,2012-08-30T00:00:00Z,UNITED MEXICAN STATES,2017-08-31T00:00:00Z,United Mexican States!$!MX,MX,United Mexican States,Mexico,...,"YA,BL,AB",IBRD,Active,N,"{'Percent': 20, 'Name': 'Biodiversity'}","[{'code': '80', 'name': 'Biodiversity'}, {'cod...","82,79,77,80",0,11690000,http://www.worldbank.org/projects/P121116/sust...
488,{'$oid': '52b213b38594d8a2be17c968'},2013,August,2012-08-30T00:00:00Z,THE STATE OF RIO DE JANEIRO,2014-01-31T00:00:00Z,Federative Republic of Brazil!$!BR,BR,Federative Republic of Brazil,Brazil,...,"JA,EZ,BH",IBRD,Closed,N,"{'Percent': 20, 'Name': 'Health system perform...","[{'code': '67', 'name': 'Health system perform...","65,28,27,67",300000000,300000000,http://www.worldbank.org/projects/P126465/rio-...
489,{'$oid': '52b213b38594d8a2be17c969'},2013,August,2012-08-30T00:00:00Z,UN-HABITAT,2015-06-30T00:00:00Z,The Independent State of Papua New Guine!$!PG,PG,The Independent State of Papua New Guine,Papua New Guinea,...,BW,IBRD,Closed,N,"{'Percent': 50, 'Name': 'Urban services and ho...","[{'code': '71', 'name': 'Urban services and ho...","73,55,52,71",0,350000,http://www.worldbank.org/projects/P128763/papu...
490,{'$oid': '52b213b38594d8a2be17c96a'},2013,August,2012-08-29T00:00:00Z,GOVERNMENT OF NEPAL,2014-06-30T00:00:00Z,Nepal!$!NP,NP,Nepal,Nepal,...,BZ,IBRD,Active,N,"{'Percent': 80, 'Name': 'Public expenditure, f...","[{'code': '27', 'name': 'Public expenditure, f...","29,27",0,800000,http://www.worldbank.org/projects/P131860/stre...
491,{'$oid': '52b213b38594d8a2be17c96b'},2013,August,2012-08-24T00:00:00Z,PALESTINIAN WATER AUTHORITY,2014-03-31T00:00:00Z,West Bank and Gaza!$!GZ,GZ,West Bank and Gaza,West Bank and Gaza,...,"WC,WA",IBRD,Active,N,"{'Percent': 100, 'Name': 'Rural services and i...","[{'code': '78', 'name': 'Rural services and in...",78,0,3650000,http://www.worldbank.org/projects/P123322/wate...

In [9]:
# Checking the count of NAN values in every column
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(x.isnull().sum())

_id                           0
approvalfy                    0
board_approval_month          0
boardapprovaldate             0
borrower                     15
closingdate                 130
country_namecode              0
countrycode                   0
countryname                   0
countryshortname              0
docty                        54
envassesmentcategorycode     70
grantamt                      0
ibrdcommamt                   0
id                            0
idacommamt                    0
impagency                    28
lendinginstr                  5
lendinginstrtype              5
lendprojectcost               0
majorsector_percent           0
mjsector_namecode             0
mjtheme                       9
mjtheme_namecode              0
mjthemecode                   0
prodline                      0
prodlinetext                  0
productlinetype               0
project_abstract            138
project_name                  0
projectdocs                  54
projectfinancialtype          0
projectstatusdisplay          0
regionname                    0
sector                        0
sector1                       0
sector2                     120
sector3                     235
sector4                     326
sector_namecode               0
sectorcode                    0
source                        0
status                        0
supplementprojectflg          2
theme1                        0
theme_namecode                9
themecode                     9
totalamt                      0
totalcommamt                  0
url                           0
dtype: int64

In [10]:
#Here I verify if any of the project names are duplicated. And hence I can group the the countries by the project names.
x.project_name.duplicated().sum()

0

In [11]:
# Checking the number of rows and columns in the dataframe 
x.shape

(500, 50)

In [12]:
#List unique values in the df['name'] column
x.project_name.unique()

array(['Ethiopia General Education Quality Improvement Project II',
       'TN: DTF Social Protection Reforms Support',
       'Tuvalu Aviation Investment Project - Additional Financing',
       "Gov't and Civil Society Organization Partnership",
       'Second Private Sector Competitiveness and Economic Diversification Prj',
       'Additional Financing for Cash Transfers for Orphans and Vulnerable Children',
       'National Highways Interconnectivity Improvement Project',
       'China Renewable Energy Scale-Up Program Phase II',
       'Rajasthan Road Sector Modernization Project',
       'MA Accountability and Transparency DPL',
       'Southern Sudan Emergency Food Crisis Response Project- AF III',
       'Uttarakhand Disaster Recovery Project', 'GH eTransform Ghana',
       'Timor Leste Road Climate Resilience Project - Additional Financing',
       'NATIONAL UNIFIED REGISTRY AND OUTREACH WORKER PROGRAM',
       'Enhanced Road Access Project',
       'Samoa Agriculture & Fisheries Cyclone Response Project',
       'Emergency Support to Education For all Project',
       'Additional Financing for the Second Health Sector Support Project',
       'DTF:MA- Support New Governance Framework',
       'SOCIAL COHESION THROUGH COMMUNITY-BASED DEVELOPMENT',
       'Nepal: Pro-poor Urban Regeneration Pilot',
       'Jordan- Emergency Services and Social Resilience',
       'Tajikistan JSDF Nutrition Grant Scale Up',
       'AGRICULTURAL COMPETITIVENESS IMPROVEMENT PROJECT',
       'Capturing Coral Reef Ecosystem Services (CCRES)',
       'Lao PDR Ninth Poverty Reduction Support Operation',
       'Pacific Aviation Safety Office Reform',
       'Additional Financing 2 - Solomon Islands Rural Development Program',
       'Water Resources Development Flood Response Additional Financing',
       'Angola Learning for All Project',
       'Kihansi Catchment Conservation and Management Project',
       'Housing Finance Development Program',
       'Sustainability and Competitiveness DPL 2',
       'Additional Financing: Skills and Training Enhancement Project',
       'SN:Casamance Development Pole Project', 'Electric Power Project',
       'West Bank and Gaza Cash Transfer Project Additional Financing',
       'Adaptation Fund: Increasing Climate Resilience & Enhancing Sustainable Land Management in the Southwest of the Buenos Aires Province',
       'GM-Integrated Financial Management and Information System Project-Additional Financing',
       'RUSSIA HYDROMETEOROLOGICAL SERVICES MODERNIZATION',
       'Congo Skills Development for Employability Project',
       'Public Finance Management Technical Assistance Project',
       'Sao Tome & Principe-Extractive Industries Transparency Initiative',
       'Solomon Islands - Extractive Industries Transparency Initiative Implementation',
       'West Africa  Regional Disease Surveillance Capacity Strengthening',
       'RCIP4 - Regional Communications Infrastructure Program - APL 4',
       'Ukraine - Smart Grid Project &#8211; PPG',
       'KM-Electricity Sect. Recovery Proj(FY14)',
       'CO: Enhancing Fiscal Capacity to Promote Shared Prosperity DPL',
       'Climate Information System and PPCR Coordination',
       'Building Resilience through Innovation, Communication & Knowledge Svcs',
       'Pacific Catastrophe Risk Assessment and Financing Initiative Phase 3 - (RETF)',
       "Cote d'Ivoire PRSC 1", "SL-RCHP2 Add'l Financing (FY13)",
       'Red Sea and Gulf of Aden Strategic Ecosystem Management GEF Project',
       'FSM and PW Telecoms & ICT TA Project',
       'Uttar Pradesh Water Sector Restructuring Project Phase 2',
       'Fighting against wildlife poaching and illegal trade in Africa',
       'Solomon Islands Development Policy Operation-2',
       'Peru - Post Compliance I', 'Agriculture Sector Support Project',
       'EC Manta Public Services Improvement Project',
       'Honduras Additional Financing Social Protection',
       'AF: Development Policy Prog. Series',
       'Regional Rusumo Falls Hydroelectric Project',
       'Municipal Solid Waste Carbon Financing Program',
       'Mauritania - TFSCB - Support to NSDS implementation',
       'LB: Mobile Internet Ecosystem Project (MIEP)', 'GZ-PNGO IV AF',
       'Tajikistan Health Services Improvement Project (HSIP)',
       'Burkina Faso Electricity Sector Support Project',
       'Montreal Protocol Hydrochlorofluorocarbons (HCFC) Phase-out Project',
       'MH:  ICT Technical Assistance Project',
       'Greater Maputo Water Supply Expansion Project',
       'Programmatic Development Policy Operation 1',
       'Financial Infrastructure Project', 'Quito Metro Line One',
       'Liberia EITI - Post Compliance I',
       'National Safety Net Program for Results',
       'State Assets Inventory and Registry',
       'Tunisia - Communications for policy reforms',
       'Mitigate the Impact of Syrian Displacement on Jordan',
       'MZ Extractive Industries Transparancy Initiative Post Compliance I',
       'Ninth Poverty Reduction Support Credit (PRSC 9)',
       'Global Partnership for Education (GPE)-4',
       'Samoa Development Policy Operation',
       'Strengthening micro-entrepreneurship for disadvantaged youth',
       'TJ-Public Procurement Capacity Building',
       'Additional Financing Health Sector Development Support Project',
       'Mali Emergency Education For All Project',
       'Morocco Microfinance Development Project',
       'Indonesia Second Power Transmission Development Project',
       'Afghanistan Agricultural Inputs Project (AAIP)',
       'Armenia Pilot Agricultural Census implementation support',
       'Guinea - MSME Development Project',
       'Nigeria Agriculture Sector Development Policy Operation',
       'THIRD NATIONAL FADAMA DEVELOPMENT PROJECT - ADDITIONAL FINANCING',
       'Nepal-India Regional Trade And Transport Project',
       'Additional Financing-West Africa Agricultural Productivity Program 2A',
       'Second Irrigation and Drainage Improvement Project',
       'EG - Helwan South Power Project',
       'NP: Financial sector stability DPC',
       'Croatia Export Financing Guarantee Operation',
       'Georgia Competitiveness and Growth DPO2',
       'AZ Integrated Solid Waste Management Project (AF)',
       'Rail Trade and Transport Facilitation AF',
       'LR-Poverty Reduction Strategy Credit I',
       'Coastal Embankment Improvement Project - Phase I (CEIP-I)',
       'TR Third Access to Finance for SMEs (SME III)',
       'Bangladesh Safety Net Systems for the Poorest Project',
       'Rio Grande do Norte: Regional Development and Governance',
       'Pernambuco Equity and Inclusive Growth DPL',
       'Cape Verde - Transport Sector Reform Project',
       'Additional Financing for Nepal-India Electricity Transmission and Trade Project',
       'Benin Cities Support Project',
       'Bangladesh: Safe Migration for Bangladeshi Workers',
       'Chad Education Sector Reform Project Phase 2',
       'Safety Net and Skills Development',
       'China: Guangdong Social Security Integration and Rural Worker Training',
       'Anhui Xuancheng Infrastructure for Industry Relocation',
       'China: Nanchang Urban Rail Project',
       'Tamil Nadu and Puducherry Coastal Disaster Risk Reduction Project',
       'HN RURAL INFRASTRUCTURE PROJECT (AF)', 'HN AF WSS Modernization',
       'Kenya Water Security and Climate Resilience Project', 'Mali RRSC',
       'Economic Reconstruction and Growth Development Policy Credit',
       'Local Government Development Program', 'Development Policy Loan 2',
       'CI - 27  Gas Field Expansion',
       'MNXTA: Enhancing Microfinance Amongst Women and Youth in MENA',
       'Belo Horizonte Urban Development Policy Loan',
       'Rio de Janeiro Strengthening Public Sector Management Technical Assistance Project',
       'Sao Paulo State Sustainable Transport Project',
       'Albania MDTF for Extractive Industry Transparency Initiative (EITI), Implementation Support, Phase III',
       'Afghanistan: Safety Nets and Pensions Support Project - AF',
       'Senegal Quality and Equity of Basic Education',
       'Indonesia Phase II: EITI Implementation',
       'Energy Sector Development Project',
       'Dem Rep Congo - Western Growth Poles',
       'DRC-Multi-Modal Transp Additional Financing',
       'Cameroon Flood Emergency Project',
       'MNXTA: Yemen Enhancing Governance through Procurement',
       'SME Revitalization and Employment Pilot Project',
       'Sustainable Land Management Project',
       'GH-GAMA Sanitation and Water Project',
       'Competitiveness and Savings Development Policy Loan (CSDPL)',
       'Natural Resources and Environmental Governance Technical Assistance',
       'Additional Financing Belarus Energy Efficiency Project',
       'Competitive Industries Project for Khyber Pakhtunkhwa',
       'Public and Social Sector Transformation Project (PSST)',
       'DJ Geothermal Power Generation Project',
       'DJ (GEF) Geothermal Power Generation Program',
       'Second Additional Financing for the Poverty Alleviation FundII Project',
       'Mongolia Livestock and Agricultural Marketing Project',
       "Ma'anshan Cihu River Basin Improvement Project",
       'Emergency Infrastructure Rehabilitation & Energy Project - Additional Financing',
       'LS- First Growth and Competitiveness DPG',
       'Second Governance and Competitiveness Development Policy Operation',
       'Fostering Innovation through Research, Science and Technology (FIRST)',
       'North East and Red River Delta Regions Health System Support Project',
       'Ningbo Municipal Solid Waste Minimization and Recycling Project',
       'Punjab Health Sector Reform Project',
       'Guangxi Laibin Water Environment Project',
       'LA-Scaling-Up Participatory Sustainable Forest Management',
       'PSG: Integrated Ecosystems Management',
       'West Africa Regional Communications Infrastructure Project - APL 2',
       'Liberia Health Systems Strengthening',
       'Lusaka Transmission and Distribution Rehabilitation Project',
       'Liberia  Accelerated Electricity Expansion Project (LACEEP)',
       'Second Education Development Policy Loan',
       'Sustainable livelihoods for displaced and vulnerable communities in Eastern Sudan',
       'Malawi Economic Recovery Development Policy Operation 1',
       'Lao PDR Customs and Trade Facilitation Project - Additional Financing',
       'NIGER COMMUNITY ACTION PROGRAM PHASE 3', 'PNPM Justice Services',
       'GZ-Second Municipal Development Project', 'WBG - PRDP Support V',
       'MENA- Desert Ecosystems and Livelihoods Knowledge Sharing and Coordination Project',
       'BF-Youth Employment & Skills Development',
       'IRRIGATION SYSTEM ENHANCEMENT PROJECT',
       'Energy Efficiency Project',
       'Uganda Energy for Rural Transformation IPF Phase2 Additional Financing',
       'Southern Africa Trade and Transport Facilitation Project',
       'Improving Maternal and Child Health through Integrated Social Services',
       'Haiti Business Development and Investment Project',
       'Development Policies for the State of Sergipe',
       'Cash Transfer Program for Vulnerable Children in Northern Togo',
       'Social Promotion And Protection Project',
       'Yemen Public Finance Modernization Project - Additional Financing',
       'Burkina Faso  Donsin Transport Infrastructure Project',
       'Nepal: School Sector Reform Program Additional Financing',
       'Sustainable Financing for Biodiversity Conservation and Natural Resources Management',
       'Kali Gandaki A Hydropower Plant Rehabilitation Project (KGAHPRP)',
       'India Low-Income Housing Finance',
       'India Second Kerala State Transport Project',
       'Integration of Children with Disabilities into Mainstream Schools',
       'Quality of Decentralized Service Delivery Support Development Policy Operation',
       'Vietnam Inclusive Innovation Project',
       'China: Jiangxi Shangrao Sanqingshan Airport Project',
       'AF - Clean-up & Land Reclamation Project',
       'ID-TF PNPM Disabled Persons Organisations Program',
       'Governance II',
       'Zambia Strengthening Climate Resilience (PPCR Phase II)',
       'DRC Urban  Development Project FY13',
       'Fourth East West Highway Improvement Project',
       'Competitiveness and Enterprise Development Project (CEDP)',
       'Additional Finaning of Public Procurement Reform Project II',
       'Public Accounting Certification Training',
       'ID-TF NATIONAL PROGRAM FOR COMMUNITY EMPOWERMENT IN RURAL AREAS HEALTHY AND BRIGHT GENERATION (PNPM GENERASI)',
       'Kyrgyz Second Health and Social Protection Project',
       'Add. Fin. - Third Water Supply and Sanitation for Low Income Communities (Community Based Water Supply/PAMSIMAS II)',
       'ZR SUPPORT TO BASIC EDUCATION PROGRAM',
       'National AIDS Control Support Project',
       'Skills Development for Growth Project',
       'Sustainable Coffee Landscape Project',
       'Emergency Safety Nets project (Jigis&#233;m&#233;jiri)',
       'Enhancing Education Development Project',
       'Second Shared Growth Credit',
       'LAOSTAT-STRENGTHENING THE NATIONAL STATISTICAL SYSTEM PROJECT',
       'Danang Sustainable City Development Project (SCDP)',
       'Second Science & Technology Project',
       'Jordan Ozone Depleting Substances HCFC Phase-Out Project (ODS3)',
       'SERBIA ROAD REHABILITATION AND SAFETY PROJECT',
       'Revenue Administration Modernization Project',
       'Urban Scale Building Energy Efficiency and Renewable Energy',
       'Additional Financing Energy Efficiency - Industrial Enterprises',
       'Zambia Water Resources Development Project',
       'Mozambique - Integrated Growth Poles Project',
       'MZ First Agriculture Development Policy Operation AgDPO-1',
       'Climate Resilience: Transforming Hydro-Meteorological Services',
       'PNPM Creative Communities II',
       'Education Sector Strategy Support Project',
       'Preparation of SREP Investment Plan',
       'LA-Nam Et-Phou Louey Tiger Landscape Conservation Project',
       'Kyrgyz Health Results Based Financing',
       'Emergency Demobilization and Transitional Reintegration Project AF',
       'National Human and Animal Health Systems Assessment Tools and Bridges',
       'Yemen: Preparation of SREP Investment Plan',
       'Lesotho Maternal & Newborn Health PBF',
       'Multi-Donor Trust Fund for PNG-IBBS',
       'Social Inclusion and Improvement of Livelihoods of Youth, Vulnerable Women and Handicapped in Post Conflict Western Cote d&#8217;Ivoire',
       'BJ-PRSC 8-Eighth Poverty Reduction Suppo',
       'PE AF Sierra Rural Development Project',
       'DJ Improving Health Sector Performance',
       'Additional Financing for Social Fund for Development IV',
       'Research and Innovation in Science and Technology Project',
       'Environmental Land Management and Rural Livelihoods Project',
       'Vietnam - Coastal Resources for Sustainable Development',
       'China GEF Large City Congestion and Carbon Reduction Project',
       'Sudan Basic Education Recovery Project',
       'Uganda Support to Municipal Infrastructure Development Program',
       'Local Governance and Service Delivery Project',
       'MZ-Social Protection project',
       'Mozambique Mining and Gas Technical Assistance Project',
       'Agricultural Competitiveness and Diversification Project',
       'Comoros Emergency Response Project (Additional Financing)',
       'Sri Lanka - Second Health Sector Development Project',
       'SME ENERGY EFFICIENCY',
       'Second DPL in support of the Plan Maroc Vert',
       'MU -Second Public Sector Performance DPL',
       'Disease Prevention and Control Project',
       'Turkey SME&#12288;Energy Efficiency Project',
       'Mauritius Second Private Sector Competitiveness DPL',
       'Tanzania Poverty Reduction Support Credit 10',
       'Second Land Administration Project (PRODEP II)',
       'Nigeria - State Education Program Investment Project',
       'Energy Sector Capacity Building Project (ESCBP)',
       'Nigeria Youth Employment & Social Support Operation',
       'Second Programmatic Development Policy Loan',
       'TZ First Power and Gas Sector DPO', 'Cameroon Social Safety Nets',
       'NE - Transp Sector Program Support Project Addit Fin',
       'Second Growth and Competitiveness Grant',
       'CN: Beijing Rooftop Solar Photovoltaic Scale-Up (Sunshine Schools) Project',
       'Liaoning Coastal Economic Zone Urban Infrastructure and Environmental Management Project',
       'CN-Jiangxi Poyang Lake Basin and Ecological Economic Zone Small Town Development Project',
       'Green Energy Schemes for Low-carbon City in Shanghai',
       'Green Energy Schemes for Low-carbon City in Shanghai, China',
       'Jiangxi Wuxikou Integrated Flood Management Project',
       'VU:  Telecommunications and ICT TA, Additional Financing',
       'Economic Management Competitiveness Credit 1',
       'PH - PH Development Policy Loan 2',
       'MH:  First ICT Sector Development Operation',
       'Afghanistan - Second Skills Development Project',
       'Emergency Agriculture Support Project',
       'Agricultural Productivity Program for Southern Africa (APPSA)',
       'Pakistan: Second Sindh Education Sector Project',
       'AF-Forest and Adjacent Land Management',
       'Rwanda Second Support to Social Protection System',
       'BJ-Forest & Adjacent Land Mgmt Addit Fin',
       'Kiribati Grid  Connected Solar PV Project',
       'Economic Competitiveness Support Program DPL',
       'Morocco Social and Integrated Agriculture',
       'Second Additional Financing to the North Sudan Decentralized Health System Development Project',
       'Sector Support for Education Reform Project',
       'Additional Financing to Health System Improvement Project',
       'MSME Development Project for Inclusive Growth',
       'ID-TF PNPM Pro-Poor Planning, Budgeting and Monitoring Program',
       'ID-PNPM Village Training Project', 'Yemen Household Budget Survey',
       'Higher Education Development Policy Program - Third Operation',
       'Vietnam School Readiness Promotion Project',
       'Ethiopia Health MDG Support Operation',
       'China:Fujian Meizhou Bay Navigation Improvement Project',
       'Afghanistan: System Enhancement for Health Action in Transition Project',
       'Community-based Livelihood Support for the Urban Poor',
       'AusAid TA for Vietnam Rural Water Supply and Sanitation PforR',
       'Reducing the Vulnerability of Small Farmers to Price Risk',
       'AFSF-Burkina Faso-FCPB', 'PNG Energy Sector Development Project',
       'GM- PG Energy Sector Development Project',
       'Rwanda Electricity Access additional Financing',
       'RY-Road Asset Management Project',
       'Building Resilience to Climate Related Hazards',
       'Solid Waste Sector DPL3',
       'Yemen: Second Basic Education Development Project',
       'Emergency Crisis Recovery Project',
       'AFSF - Asia - Cambodia - AMRET',
       'Nepal Agriculture and Food Security Project',
       'Climate Resilient Participatory Afforestation and Reforestation Project',
       'Solid Waste Management OBA Pilot in West Bank',
       'Kazakhstan - Youth Corps program',
       'Health Sector Strategic Plan Support Additional Financing',
       'PEFA Study for Local Governments in Croatia',
       'Improving Resilience to Seismic Risk',
       'Enhancing the Climate Resilience of the West Coast Road',
       'Microfinance Development Project',
       'Sierra Leone Energy Access Project - Sierra Leone Infrastructure Development Fund',
       'LIFELINE ROAD NETWORK IMPROVEMENT PROJECT',
       'Emergency Livestock Feed Access Project',
       'JSDF Strengthening the Livelihoods and Voice of Vulnerable and Disabled Persons in Armenia',

In [13]:
# Grouping all countries by the number of unique projects they have
df = x.groupby('countryname')['project_name'].nunique()

In [14]:
#Checking the type of df
type(df)

pandas.core.series.Series

In [15]:

# Converting df (which is of Series type) to Pandas Dataframe type
df1=pd.DataFrame(df)
# Renaming the Column Names
df1.columns = ['Project Count']

In [16]:
# Sorting the dataframe by the project count
df1=df1.sort_values(by=['Project Count'],ascending=False, na_position='first')
df1.head(10)

                                 Project Count
countryname
People's Republic of China                  19
Republic of Indonesia                       19
Socialist Republic of Vietnam               17
Republic of India                           16
Republic of Yemen                           13
People's Republic of Bangladesh             12
Nepal                                       12
Kingdom of Morocco                          12
Republic of Mozambique                      11
Africa                                      11

#### Find the top 10 major project themes (using column 'mjtheme_namecode')

In [50]:
#Loading the JSON data 
r = json.load((open('world_bank_projects.json')))
y=json_normalize(r, 'mjtheme_namecode')

In [51]:
# Checking the count of NAN values in every column
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(y.isnull().sum())

code    0
name    0
dtype: int64

In [52]:
# Re-ordering the columns 
y = y[['name', 'code']]

In [53]:
# Checking the data types of each column
y.dtypes

name    object
code    object
dtype: object

In [54]:
# Re-checking the data types of each column
y[['code']] = y[['code']].apply(pd.to_numeric)
y.dtypes

name    object
code     int64
dtype: object

In [60]:
# Checking the contents of the data frame
y.head()

                                    name  code
0                      Human development     8
1                                           11
2                    Economic management     1
3  Social protection and risk management     6
4                  Trade and integration     5

In [62]:
x=y.groupby(['name']).agg(['count'])
x.head(10)

                                              code
                                             count
name
                                               122
Economic management                             33
Environment and natural resources management   223
Financial and private sector development       130
Human development                              197
Public sector governance                       184
Rule of law                                     12
Rural development                              202
Social dev/gender/inclusion                    119
Social protection and risk management          158

#### In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [109]:
#Reloading the JSON data and saving it in the form of a DataFrame
r = json.load((open('world_bank_projects.json')))
y=json_normalize(r, 'mjtheme_namecode')

In [110]:
# Checking the count of NAN values in every column
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(y.isnull().sum())

code    0
name    0
dtype: int64

In [111]:
# Re-ordering the columns 
y = y[['name', 'code']]

In [112]:
# Re-checking the data types of each column
y[['code']] = y[['code']].apply(pd.to_numeric)
y.dtypes

name    object
code     int64
dtype: object

In [113]:
# Checking the contents of the data frame
y.head()

                                    name  code
0                      Human development     8
1                                           11
2                    Economic management     1
3  Social protection and risk management     6
4                  Trade and integration     5

In [114]:
# Filtering the y dataframe by the name of the column
z=y.loc[y['code'] == 11]
# Changing the obtained Series Type to Pandas DataFrame type 
z = pd.DataFrame(z)

In [115]:
# Checking the contents of the data frame
z.head()

                                            name  code
1                                                   11
6   Environment and natural resources management    11
16  Environment and natural resources management    11
28  Environment and natural resources management    11
31  Environment and natural resources management    11

##### It is clear that the missing entry for names column is 'Environment and natural resources management'. Hence we'll start filling up the above mentioned entry wherever there is a blank space.

In [123]:
#Substituting empty spaces with specific values
Final=y.replace('', 'Environment and natural resources management')
#Converting the obtained Series into Dataframe
Final = pd.DataFrame(Final)
Final.head()

                                           name  code
0                             Human development     8
1  Environment and natural resources management    11
2                           Economic management     1
3         Social protection and risk management     6
4                         Trade and integration     5

In [126]:
Final['name'][Final['name'] == ''].count()

0

### Hence there are no empty values in the names column in the dataframe